### ISSUE TITLE
"pl": "one", "few", "many", "other"

### ISSUE THREAD

**Issue by doublex** [mlocati/cldr-to-gettext-plural-rules#10]
CLDR 30:
````
<pluralRule count="one">i = 1 and v = 0 @integer 1</pluralRule>
<pluralRule count="few">v = 0 and i % 10 = 2..4 and i % 100 != 12..14 @integer 2~4, 22~24, 32~34, 42~44, 52~54, 62, 102, 1002, …</pluralRule>
<pluralRule count="many">v = 0 and i != 1 and i % 10 = 0..1 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 12..14 @integer 0, 5~19, 100, 1000, 10000, 100000, 1000000, …</pluralRule>
<pluralRule count="other">   @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …</pluralRule>
````

On this page "pl" has only "one", "few" and "other":
http://mlocati.github.io/cldr-to-gettext-plural-rules/

**Comment by mlocati** [comment]
This is the intended behavior: as you can see from the rules, the CLDR case for "other" never occurs for integer numbers.
So, since gettext only works with integers, that case is meaningless in .po files.
For that reason, the "other" CLDR case is removed and in gettext the "many" is renamed to "other".

See also this discussion I've had with Daiki Ueno, the official maintainer of gettext: http://lists.gnu.org/archive/html/bug-gettext/2015-05/msg00007.html

**Comment by doublex** [comment]
You are right - I have miss-understood the formular.
If "v = 0" you have only 3 rules.
Sorry for disturbing.

**Comment by mlocati** [comment]
No problems at all!

Ciao!

**Comment by doublex** [comment]
Thanks a lot for this great code!
